name: Go Backend CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Set up environment variables
        run: |
          echo "MONGO_URI=mongodb://localhost:27017/testdb" >> $GITHUB_ENV
          echo "JWT_SECRET=supersecret" >> $GITHUB_ENV
          echo "SENDGRID_API_KEY=dummy" >> $GITHUB_ENV
          echo "SENDGRID_FROM_EMAIL=dummy@example.com" >> $GITHUB_ENV
          echo "TWILIO_ACCOUNT_SID=dummy" >> $GITHUB_ENV
          echo "TWILIO_AUTH_TOKEN=dummy" >> $GITHUB_ENV
          echo "TWILIO_PHONE_NUMBER=+10000000000" >> $GITHUB_ENV

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...